---
- name: Install SNCSEQ
  include_tasks: "{{ epics_build_module_task }}"
  vars:
    epics_modules_to_build: "{{ m_seq_modules }}"
  when: not (m_seq_installed | default(false))

- name: Mark m-seq as installed
  set_fact:
    m_seq_installed: true
