# Install Tomcat
---
- name: Ensure tomcat_home directory exists
  become: true
  file:
    path: "{{ tomcat_home }}"
    state: directory
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

- name: Check if Tomcat installation exists
  become: true
  stat:
    path: "{{ tomcat_home }}/bin/catalina.sh"
  register: tomcat_installation
  changed_when: false

- name: Download and install Tomcat
  become: true
  ansible.builtin.unarchive:
    src: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_home }}"
    remote_src: true
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    extra_opts:
      - --strip-components=1
  when: tomcat_installation.stat.exists == false
