# defaults for phoebus
---
phoebus_version: v5.0.2

phoebus_launcher: "/opt/epics-tools/lib/phoebus/phoebus-product/phoebus.sh"
phoebus_owner: "root"
force_gpu: false

# JAVA options
phoebus_java_initial_heapsize: "256M"
phoebus_java_max_heapsize: "1024M"
phoebus_java_heap_tuning_opts: "-XX:MaxHeapFreeRatio=10 -XX:MinHeapFreeRatio=5 -XX:-ShrinkHeapInSteps"

mvn_version: 3.9.14
mvn_home: "/opt/epics-tools/lib/apache-maven"

epics_services_account: root
