---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
  inventory:
    host_vars:
      initial_setup-docker:
        in_container: true
        docker: true
    group_vars:
      all:

scenario:
  name: default
verifier:
  name: testinfra
  directory: ../resources/tests/
driver:
  name: docker
platforms:
  - name: initial_setup-docker
    image: ubuntu:22.04
