# Default configuration for all Ansible runs
# (most settings will be overridden per host or role)

# Setting all module switches to false (just make sure the variables exist)
initial_setup: false
docker: false # for rootful this needs to happen before first reboot
epics_modules_build: false
catrust: false
epics_tools: false
oac_tree: false
archiver_appliance: false
bluesky: false

# Default configuration for the EPICS modules to build = minimal
epics_modules_list:
  - base
  - pvxs

# Default: false proxy
proxy_env: {}

# when building inside a container during CI this is set to true
in_container: false
