---
- name: Load distribution variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"

- name: Print all available facts for debugging
  # 'cd ansible; ansible localhost -m ansible.builtin.setup' will show this info
  ansible.builtin.debug:
    var: ansible_facts

- name: APT Upgrade all packages; install Dev Tools and Gnome
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  block:
    - name: APT Update and upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
        autoclean: true
        autoremove: true

    - name: APT Install Dev Tools
      ansible.builtin.apt:
        name:
          - build-essential
          - git
          - vim
          - curl
          - sudo
          - openssl

    - name: APT Install Gnome
      ansible.builtin.apt:
        name:
          - "{{ initial_setup_gnome_group }}"
      when: install_graphics | bool

- name: RPM Upgrade all packages; install Dev Tools and Gnome
  when: ansible_facts['os_family'] == 'RedHat'
  become: true
  block:
    - name: RPM Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true

    - name: RPM Install Dev Tools
      ansible.builtin.dnf:
        name:
          - "@{{ initial_setup_devel_group }}"
          - gcc-c++
          - vim
          - sudo
          - openssl
        allowerasing: true # fix version conflicts for curl and coreutils on Rocky
        install_weak_deps: false

    - name: RPM Install Gnome
      ansible.builtin.dnf:
        name:
          - "@{{ initial_setup_gnome_group }}"
        allowerasing: true
        install_weak_deps: false
      when: install_graphics | bool

    - name: RPM clean cache
      ansible.builtin.command: dnf clean all

- name: Set default to graphical target
  when: not in_container and install_graphics | bool
  become: true
  block:
# Source - https://stackoverflow.com/a/72196011
# Posted by TRW, modified by community. See post 'Timeline' for change history
# Retrieved 2026-07-01, License - CC BY-SA 4.0
    - name: "Get current systemd default" # noqa: command-instead-of-module
      ansible.builtin.command: "systemctl get-default"
      changed_when: false
      register: systemdefault

    - name: "Set default to graphical target"
      ansible.builtin.command: "systemctl set-default graphical.target"
      when: "'graphical' not in systemdefault.stdout"
      changed_when: true

- name: Create development user
  ansible.builtin.user:
    name: "{{ dev_user }}"
    shell: /bin/bash
    createhome: true
    password: ""
    comment: "EPICS Developer"
  become: true

- name: Make development user passwordless for sudo in group wheel
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: "^%{{ dev_user }}"
    line: "%{{ dev_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  become: true

- name: Ensure that python refers to python3
  ansible.builtin.file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
  become: true

- name: Disable SELinux (on RedHat)
  when: ansible_facts['os_family'] == 'RedHat'
  become: true
  ansible.posix.selinux:
    state: disabled
    update_kernel_param: true

- name: Disable firewall (on RedHat)
  when: ansible_facts['os_family'] == 'RedHat'
  become: true
  ansible.builtin.systemd_service:
    name: firewalld.service
    state: stopped
    enabled: false
