---
# Defaults for Phoebus (and Maven)

# build switch default (inventory setting overrides)
epics_tools: false

phoebus_version: 8728dbb

phoebus_launcher: "/opt/epics-tools/lib/phoebus/phoebus-product/phoebus.sh"
phoebus_owner: "root"
force_gpu: false

mvn_home: "/opt/epics-tools/lib/apache-maven"
