
name: Debian 12 Flavor

on:
  push:
    paths:
      - '.github/workflows/ci-debian.yml'
      - '.github/workflows/generic-ci.yml'
      - '.github/workflows/Containerfile.debian'
      - 'ansible/**'
      - 'initial_setup.sh'
      - 'update.sh'
  pull_request:
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/_check.yml
  ci-debian:
    needs: check
    if: needs.check.outputs.branch-pr == ''
    uses: ./.github/workflows/generic-ci.yml
    with:
      distro: debian
      image: 'debian:12'
