ARG IMAGE=debian:latest

FROM ${IMAGE}
ENV DEBIAN_FRONTEND=noninteractive

COPY ansible /ansible
WORKDIR /ansible

RUN apt-get update && apt-get install -y git ansible ansible-lint

RUN ansible-galaxy install -r requirements.yml || true
RUN ansible-playbook playbook.yml -e "@vars/ci-base-image.yml"

RUN rm -fr /ansible
