ARG IMAGE

FROM ${IMAGE}

RUN dnf install -y epel-release || dnf update -y --refresh
RUN dnf install -y git python3-pip python3-jmespath ansible
RUN pip3 install ansible-lint

COPY ansible /ansible
WORKDIR /ansible

RUN ansible-galaxy install -r requirements.yml || true
RUN ansible-playbook playbook.yml -e "setup=ci-base-image"

RUN rm -fr /ansible
