ARG IMAGE

FROM ${IMAGE}
ENV DEBIAN_FRONTEND=noninteractive

COPY ansible /ansible

RUN apt-get update && apt-get install -y git ansible ansible-lint

RUN ansible-galaxy install -r /ansible/requirements.yml || true
RUN ansible-playbook /ansible/playbook.yml -e "setup=ci-base-image"

RUN rm -fr /ansible
