ARG IMAGE

FROM $IMAGE
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install -y software-properties-common \
 && add-apt-repository ppa:ansible/ansible \
 && apt-get install -y git ansible ansible-lint

COPY ansible /ansible

RUN ansible-galaxy install -r /ansible/requirements.yml || true
RUN ansible-playbook /ansible/playbook.yml -e "setup=ci-base-image"

RUN rm -fr /ansible
