name: "Test Roles: Phoebus & AA"

on:
  push:
    paths:
      - '.github/workflows/test-roles-phoebus-aa.yml'
      - 'ansible/vars/ci-*.yml'
      - 'ansible/playbook.yml'
      - 'ansible/requirements.yml'
      - 'ansible/roles/epics-tools/**'
      - 'ansible/roles/java/**'
  pull_request:
    paths:
    - '.github/workflows/test-roles-phoebus-aa.yml'
    - 'ansible/vars/ci-*.yml'
    - 'ansible/playbook.yml'
    - 'ansible/requirements.yml'
    - 'ansible/roles/epics-tools/**'
    - 'ansible/roles/java/**'
  workflow_run:
    workflows: ["Rebuild Container Images"]
    types:
      - completed
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  wait:
    uses: ./.github/workflows/_wait_for_workflow.yml
    with:
      workflow_name: "rebuild-container-images"
      sha: ${{ github.sha }}

  prep:
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.lowercase.outputs.repo_name }}
    steps:
      - id: lowercase
        run: echo "repo_name=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

  test:
    needs: [check, wait, prep]
    name: "${{ matrix.distro }}: ${{ matrix.conf.name }}"
    if: |
      (github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success')
    strategy:
      fail-fast: false
      matrix:
        distro: [ubuntu, rocky, debian, fedora]
        conf:
          - name: "Phoebus & Archiver"
            id: "ci-phoebus-aa"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download image artifact
        if: needs.wait.outputs.artifact_exists == 'true'
        uses: actions/download-artifact@v4
        with:
          name: epics-training-base-${{ matrix.distro }}-image
          path: /tmp

      - name: Load image
        if: needs.wait.outputs.artifact_exists == 'true'
        run: docker load -i /tmp/epics-training-base-${{ matrix.distro }}-image.tar

      - name: Build ${{ matrix.conf.name }}
        run: |
          IMAGE="ghcr.io/${{ needs.prep.outputs.repo_name }}/epics-training-base-${{ matrix.distro }}:latest"
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/ansible $IMAGE \
            ansible-playbook -v playbook.yml -e "@vars/${{ matrix.conf.id }}.yml"
